if command -v uwsm >/dev/null && uwsm check may-start; then
    exec uwsm start hyprland.desktop
fi

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
