if command -v uwsm >/dev/null && uwsm check may-start; then
    exec uwsm start hyprland.desktop
fi

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
# The 'python' module is optional, so pyenv is not always installed. WSL also
# inherits the Windows PATH, which can put a pyenv-win shim on it; that shim
# only knows how to call cmd.exe, so ignore any pyenv under /mnt.
if pyenv_bin=$(command -v pyenv) && [[ $pyenv_bin != /mnt/* ]]; then
	eval "$(pyenv init - zsh)"
fi
unset pyenv_bin
