#!/bin/bash

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COLORS_DIR="$SCRIPT_DIR/../colors"

INPUT="$COLORS_DIR/colors.txt"
CSS_OUT="$COLORS_DIR/colors.css"
CONF_OUT="$COLORS_DIR/colors.conf"
RASI_OUT="$COLORS_DIR/colors.rasi"

# Create or overwrite output files
echo "/* Automatically generated by generate-colors.sh */" > "$CSS_OUT"
echo "# Automatically generated by generate-colors.sh" > "$CONF_OUT"
echo "/* Automatically generated by generate-colors.sh */" > "$RASI_OUT"

# Open rasi block
echo "* {" >> "$RASI_OUT"

hex_to_rgba() {
    hex=${1#"#"}
    r=$((16#${hex:0:2}))
    g=$((16#${hex:2:2}))
    b=$((16#${hex:4:2}))
    if [[ ${#hex} -eq 8 ]]; then
        a=$(printf "%.2f" "$((16#${hex:6:2})) / 255")
    else
        a=1.0
    fi
    echo "rgba($r,$g,$b,$a)"
}

# Parse input
while IFS= read -r line; do
    # Skip empty lines
    [[ -z "$line" ]] && continue

    # Only process lines like: @export name #hex;
    if [[ $line =~ @export[[:space:]]+([a-zA-Z0-9-]+)[[:space:]]+(#[a-fA-F0-9]{6})\; ]]; then
        name="${BASH_REMATCH[1]}"

        hex="${BASH_REMATCH[2]}"
        hex_transparent="${hex}55"  # Add transparency to hex
        
        rgba=$(hex_to_rgba "$hex")
        rgba_transparent=$(hex_to_rgba "$hex_transparent")

        # Write to CSS
        echo "@define-color $name $hex;" >> "$CSS_OUT"

        # Write to Hyprland config
        echo "\$$name = $rgba" >> "$CONF_OUT"

        # Write to Rofi Rasi
        echo -e "\t$name: $hex;" >> "$RASI_OUT"
        echo -e "\t${name}-transparent: $hex_transparent;" >> "$RASI_OUT"

        echo "" >> "$CSS_OUT"
        echo "" >> "$CONF_OUT"
        echo "" >> "$RASI_OUT"
    fi
done < "$INPUT"

# Close rasi block
echo "}" >> "$RASI_OUT"
