#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/../../lib/common.sh"

WSL_CONF="/etc/wsl.conf"

# appendWindowsPath is deliberately left at its default (on): dropping the
# Windows PATH also drops the interop binaries worth having from a terminal --
# clip.exe, explorer.exe, code.
WSL_CONF_BODY="# Generated by install-scripts/modules/wsl/install-wslconf.sh -- edit there.

# WSL boots its own init by default, which leaves systemctl, user units and
# timers unavailable.
[boot]
systemd = true

# Without metadata every file under /mnt/c is 0777 root:root, so chmod is
# silently a no-op and git reports a mode change on every Windows-side file.
[automount]
options = \"metadata,umask=22,fmask=11\"

# wsl.exe logs in as root unless a default user is named.
[user]
default = $USER"

# tee writes as root from inside a pipe, so cache the credentials first.
prime_sudo

needs_restart=false
if [ "$(cat "$WSL_CONF" 2>/dev/null)" != "$WSL_CONF_BODY" ]; then
    needs_restart=true
fi

write_root_file "$WSL_CONF" "$WSL_CONF_BODY"
ok "wsl.conf configured"

# wsl.conf is only read when the distro starts, and nothing inside the distro
# can restart it.
if [ "$needs_restart" = true ] && [ "${DRY_RUN}" != true ]; then
    warn "run 'wsl --shutdown' from Windows for $WSL_CONF to take effect"
fi
