--  _   _                  _                 _
-- | | | |_   _ _ __  _ __| | __ _ _ __   __| |
-- | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
-- |  _  | |_| | |_) | |  | | (_| | | | | (_| |
-- |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
--        |___/|_|
--
-- Full documentation: https://wiki.hypr.land

_G.colors = dofile(os.getenv("HOME") .. "/.config/hypr/colors.lua")

-- Every machine gets the defaults; machine.lua (generated by the installer
-- from the machine profile) then layers that machine's overrides on top.
local defaults = {
    "animations", "autostart", "bindings", "decorations", "input", "layouts",
    "layout-even", "monitor", "permissions", "render", "windowrules",
}
for _, name in ipairs(defaults) do
    require("config.default." .. name)
end

require("machine")
