[ids]
*

[main]
capslock = overload(extend, esc)

[extend]
# --- modifiers ---
f = layer(meta)

# --- Navigation (Colemak UNEI -> Arrow Keys) ---
i = up
j = left
k = down
l = right

# --- Editing ---
; = backspace
p = delete

# --- Standard Shortcuts ---
u = home
y = pageup
h = pagedown
o = end
