# Ignore maximize requests from apps.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Start vivaldi and firefox in fake fullscreen
windowrule = fullscreenstate 0 2, firefox
windowrule = fullscreenstate 0 2, Vivaldi-stable
windowrulev2 = bordercolor rgb(FFFF00), fullscreenstate:* 2 