#!/bin/bash

# Install base packages
sudo pacman -S --needed --noconfirm git github-cli
yay -S --needed --noconfirm visual-studio-code-bin

# Python
sudo pacman -S --needed --noconfirm base-devel openssl zlib xz tk pyenv
yay -S --needed --noconfirm pyenv-virtualenv
pyenv install 3.12.11 --skip-existing

# Nodejs
sudo pacman -S --needed --noconfirm nodejs npm

# Unity
sudo pacman -S --needed --noconfirm dotnet-runtime dotnet-sdk mono-msbuild mono-msbuild-sdkresolver mono aspnet-runtime
yay -S --needed --noconfirm unityhub

# Blender
sudo pacman -S --needed --noconfirm blender cuda

# Docker
sudo pacman -S --needed --noconfirm docker docker-compose nvidia-container-toolkit docker-buildx

sudo usermod -aG docker $USER             # Add user to docker group, enabling docker commands without sudo
sudo systemctl enable --now docker.socket # Enable Docker socket for on-demand use

sudo nvidia-ctk runtime configure --runtime=docker
sudo systemctl restart docker.socket

# bash configuration
if ! grep -q 'export PYENV_ROOT="$HOME/.pyenv"' ~/.bashrc; then
  cat << 'EOF' >> ~/.bashrc

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"
eval "$(pyenv virtualenv-init -)"
EOF
fi

if ! grep -q 'export PYENV_ROOT="$HOME/.pyenv"' ~/.bash_profile; then
  cat << 'EOF' >> ~/.bash_profile

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"
EOF
fi

# zsh configuration
if ! grep -q 'export PYENV_ROOT="$HOME/.pyenv"' ~/.zshrc; then
  cat << 'EOF' >> ~/.zshrc

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
eval "$(pyenv virtualenv-init -)"
EOF
fi

if ! grep -q 'export PYENV_ROOT="$HOME/.pyenv"' ~/.zprofile; then
  cat << 'EOF' >> ~/.zprofile

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
EOF
fi