#!/bin/bash

# Install base packages
sudo pacman -S --needed --noconfirm git github-cli
yay -S --needed --noconfirm visual-studio-code-bin

# install python
sudo pacman -S --needed --noconfirm base-devel openssl zlib xz tk pyenv
pyenv install 3.12 --skip-existing

if ! grep -q 'export PYENV_ROOT="$HOME/.pyenv"' ~/.bashrc; then
  cat << 'EOF' >> ~/.bashrc

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"
EOF
fi

if ! grep -q 'export PYENV_ROOT="$HOME/.pyenv"' ~/.bash_profile; then
  cat << 'EOF' >> ~/.bash_profile

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"
EOF
fi