# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = eDP-2, disable
monitor = DP-3,  preferred, auto, auto
monitor = DP-4,  preferred, auto, auto

workspace = 1, monitor:DP-4, persistent:true
workspace = 2, monitor:DP-4, persistent:true
workspace = 3, monitor:DP-4, persistent:true
workspace = 4, monitor:DP-4, persistent:true
workspace = 5, monitor:DP-4, persistent:true
workspace = 6, monitor:DP-3, persistent:true