#!/usr/bin/env python3
"""Fill theme/templates/* with the active palette from theme/palettes.toml."""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
THEME_DIR = REPO / "theme"
PALETTES_TOML = THEME_DIR / "palettes.toml"
TEMPLATE_DIR = THEME_DIR / "templates"
STATE_FILE = Path.home() / ".local" / "state" / "dotfiles" / "theme"

BANNER = "Generated by theme/generate.py from theme/palettes.toml - do not edit."

UI_KEYS = [
    "base", "mantle", "surface", "surfaceAlt", "overlay", "border",
    "text", "subtext", "accent", "onAccent",
]
ANSI_KEYS = [
    "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
    "brightBlack", "brightRed", "brightGreen", "brightYellow",
    "brightBlue", "brightMagenta", "brightCyan", "brightWhite",
]

# {{accent}} -> #fabd2f, {{accent:50}} -> #fabd2f80 (alpha percent),
# {{accent:mix45}} -> #9c7a2c (45% toward base), {{accent:rgb}} -> rgb(fabd2f).
# Filters chain left to right, so colour maths goes before the output format.
PLACEHOLDER = re.compile(r"\{\{(\w+)((?::\w+)*)\}\}")


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def load_config() -> dict:
    if not PALETTES_TOML.is_file():
        die(f"{PALETTES_TOML} not found")
    with PALETTES_TOML.open("rb") as fh:
        cfg = tomllib.load(fh)

    palettes = cfg.get("palettes")
    if not palettes:
        die("palettes.toml defines no [palettes.*] tables")

    for name, palette in palettes.items():
        if "label" not in palette:
            die(f"palette '{name}' is missing 'label'")
        for section, expected in (("ui", UI_KEYS), ("ansi", ANSI_KEYS)):
            got = palette.get(section)
            if got is None:
                die(f"palette '{name}' is missing the [{section}] section")
            missing = [k for k in expected if k not in got]
            if missing:
                die(f"palette '{name}' [{section}] is missing: {', '.join(missing)}")
            unknown = [k for k in got if k not in expected]
            if unknown:
                die(f"palette '{name}' [{section}] has unknown keys: {', '.join(unknown)}")

    default = cfg.get("default")
    if default not in palettes:
        die(f"default palette '{default}' is not defined")

    outputs = cfg.get("outputs")
    if not outputs:
        die("palettes.toml defines no [outputs] table")
    for template in outputs:
        if not (TEMPLATE_DIR / template).is_file():
            die(f"[outputs] names a missing template: theme/templates/{template}")

    return cfg


def resolve_palette(cfg: dict, requested: str | None) -> str:
    if requested:
        if requested not in cfg["palettes"]:
            valid = ", ".join(cfg["palettes"])
            die(f"unknown palette '{requested}' (available: {valid})")
        return requested

    if STATE_FILE.is_file():
        name = STATE_FILE.read_text().strip()
        if name in cfg["palettes"]:
            return name
        print(f"warning: state file names unknown palette '{name}', using default",
              file=sys.stderr)

    return cfg["default"]


def mix(color: str, target: str, percent: int) -> str:
    a, b = color.lstrip("#"), target.lstrip("#")
    channels = [
        round(int(a[i:i + 2], 16) + (int(b[i:i + 2], 16) - int(a[i:i + 2], 16)) * percent / 100)
        for i in (0, 2, 4)
    ]
    return "#" + "".join(f"{c:02x}" for c in channels)


def apply_filter(value: str, spec: str, values: dict[str, str], where: str) -> str:
    if spec == "rgb":
        return f"rgb({value.lstrip('#')})"
    if spec.isdigit():
        return f"{value}{round(int(spec) * 255 / 100):02x}"
    if spec.startswith("mix") and spec[3:].isdigit():
        return mix(value, values["base"], int(spec[3:]))
    die(f"{where}: unknown filter '{spec}'")


def render(template: str, name: str, values: dict[str, str]) -> str:
    def replace(match: re.Match) -> str:
        key, specs = match.group(1), match.group(2)
        if key not in values:
            die(f"{name}: unknown placeholder '{key}'")
        value = values[key]
        for spec in filter(None, specs.split(":")):
            value = apply_filter(value, spec, values, f"{name}: {{{{{key}}}}}")
        return value

    return PLACEHOLDER.sub(replace, template)


def write_if_changed(path: Path, content: str, dry_run: bool) -> None:
    if path.is_file() and path.read_text() == content:
        print(f"  unchanged  {path.relative_to(REPO)}")
        return
    if dry_run:
        print(f"  [dry-run]  {path.relative_to(REPO)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote      {path.relative_to(REPO)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-p", "--palette",
                        help="palette to activate (default: the state file, then palettes.toml)")
    parser.add_argument("-n", "--dry-run", action="store_true",
                        help="report what would be written, change nothing")
    parser.add_argument("-l", "--list", action="store_true",
                        help="print available palette names, one per line")
    args = parser.parse_args()

    cfg = load_config()

    if args.list:
        for palette_name in cfg["palettes"]:
            print(palette_name)
        return 0

    name = resolve_palette(cfg, args.palette)
    palette = cfg["palettes"][name]
    values = {
        **palette["ui"],
        **palette["ansi"],
        "name": name,
        "label": palette["label"],
        "banner": BANNER,
    }

    # Render everything up front so a broken template can't leave the system
    # half-themed.
    rendered = [
        (REPO / target, render((TEMPLATE_DIR / template).read_text(), template, values))
        for template, target in cfg["outputs"].items()
    ]

    print(f":: Generating theme configs for {palette['label']} ({name})")
    for path, content in rendered:
        write_if_changed(path, content, args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
