#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

eval "$(starship init bash)"

# Pyenv configuration - Auto generated by dev_environment_install.sh
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
# The 'python' module is optional, so pyenv is not always installed.
if command -v pyenv >/dev/null; then
	eval "$(pyenv init - bash)"
	# starship shows the venv name in [python]; don't also prepend it to PS1.
	export PYENV_VIRTUALENV_DISABLE_PROMPT=1
	eval "$(pyenv virtualenv-init -)"
fi
