#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/../../lib/common.sh"

load_profile

if [ -z "$ETH_INTERFACE" ]; then
    ok "no wired interface in the '$MACHINE' profile; networkd left alone"
    exit 0
fi

WAIT_ONLINE_DIR="/etc/systemd/system/systemd-networkd-wait-online.service.d"
WAIT_ONLINE_CONF="$WAIT_ONLINE_DIR/override.conf"
IGNORE_WIFI_CONF="/etc/systemd/network/99-ignore-wifi.network"

# wait-online waits for every managed interface by default, including wifi with
# no carrier, which stalls everything ordered after network-online (docker,
# rclone) until it times out. Only the wired interface counts.
WAIT_ONLINE_BODY="# Generated by install-scripts/modules/base/install-networkd.sh -- edit there.
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --interface=$ETH_INTERFACE"

# Unmanaged, wifi no longer shows up as a stray 'configuring' interface.
IGNORE_WIFI_BODY="# Generated by install-scripts/modules/base/install-networkd.sh -- edit there.
[Match]
Name=wl*

[Link]
Unmanaged=yes"

prime_sudo

changed=false
if [ "$(cat "$WAIT_ONLINE_CONF" 2>/dev/null)" != "$WAIT_ONLINE_BODY" ] ||
    [ "$(cat "$IGNORE_WIFI_CONF" 2>/dev/null)" != "$IGNORE_WIFI_BODY" ]; then
    changed=true
fi

run_cmd sudo mkdir -p "$WAIT_ONLINE_DIR"
write_root_file "$WAIT_ONLINE_CONF" "$WAIT_ONLINE_BODY"
write_root_file "$IGNORE_WIFI_CONF" "$IGNORE_WIFI_BODY"

if [ "$changed" = true ]; then
    info "Reloading systemd and restarting networkd..."
    run_cmd sudo systemctl daemon-reload
    run_cmd sudo systemctl restart systemd-networkd
fi

ok "networkd configured for $ETH_INTERFACE"
