#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/../../lib/common.sh"

require_cmd mkinitcpio

NVIDIA_MODULES="nvidia nvidia_modeset nvidia_uvm nvidia_drm"
MODPROBE_CONF="/etc/modprobe.d/nvidia.conf"

MODPROBE_BODY="# Generated by install-scripts/modules/base/install-nvidia.sh -- edit there.
#
# UsePageAttributeTable: map GPU-shared memory through the CPU's PAT instead of
# the older MTRR path. Cheaper CPU->GPU transfers.
# DynamicPowerManagement: 0 turns off runtime D3. It is a laptop feature; on a
# desktop driving displays from the dGPU it only adds power-state transitions.
options nvidia NVreg_UsePageAttributeTable=1
options nvidia NVreg_DynamicPowerManagement=0"

install_packages \
    nvidia-open \
    nvidia-utils \
    lib32-nvidia-utils \
    nvidia-settings \
    egl-wayland

# write_root_file runs sudo tee inside a pipe, so credentials must already
# be cached.
prime_sudo

# Both the early-KMS module list and modprobe.d are baked into the initramfs
# (the latter by the modconf hook), so either change needs a rebuild.
needs_initramfs=false

if grep -qE '^MODULES=\(.*\bnvidia\b' /etc/mkinitcpio.conf; then
    ok "NVIDIA early KMS modules already in mkinitcpio.conf"
else
    info "Adding NVIDIA early KMS modules to mkinitcpio.conf..."
    run_cmd sudo sed -i "s/^MODULES=(/MODULES=($NVIDIA_MODULES /" /etc/mkinitcpio.conf
    needs_initramfs=true
fi

if [ "$(cat "$MODPROBE_CONF" 2>/dev/null)" != "$MODPROBE_BODY" ]; then
    needs_initramfs=true
fi
write_root_file "$MODPROBE_CONF" "$MODPROBE_BODY"

if [ "$needs_initramfs" = true ]; then
    info "Regenerating initramfs for the NVIDIA changes..."
    run_quiet sudo mkinitcpio -P
fi

ok "nvidia configured"

if [ "$needs_initramfs" = true ]; then
    warn "reboot required for the NVIDIA changes to take effect"
fi
