#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/../../lib/common.sh"

# starship.toml is generated by the 'theme' aspect, which runs before this one.
install_packages \
    starship

stow_config starship ~/.config/starship.toml
