#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/../../lib/common.sh"

require_cmd mkinitcpio
require_cmd sysctl

MODPROBE_CONF="/etc/modprobe.d/nvidia.conf"
SYSCTL_CONF="/etc/sysctl.d/99-gaming.conf"

MODPROBE_BODY="# Generated by install-scripts/modules/base/install-tunables.sh -- edit there.
#
# UsePageAttributeTable: map GPU-shared memory through the CPU's PAT instead of
# the older MTRR path. Cheaper CPU->GPU transfers.
# DynamicPowerManagement: 0 turns off runtime D3. It is a laptop feature; on a
# desktop driving displays from the dGPU it only adds power-state transitions.
options nvidia NVreg_UsePageAttributeTable=1
options nvidia NVreg_DynamicPowerManagement=0"

SYSCTL_BODY="# Generated by install-scripts/modules/base/install-tunables.sh -- edit there.
#
# split_lock_mitigate does not prevent split locks, it penalises the process
# that takes one with a forced delay. Windows games under Proton trigger them
# routinely, which shows up as periodic hitching at a healthy average FPS.
kernel.split_lock_mitigate = 0

# Stop the kernel paging out game memory it thinks is cold during a long
# session; touching it again later is a stall.
vm.swappiness = 10"

# write_root_file runs sudo tee inside a pipe, so credentials must already
# be cached.
prime_sudo

needs_initramfs=false
if [ "$(cat "$MODPROBE_CONF" 2>/dev/null)" != "$MODPROBE_BODY" ]; then
    needs_initramfs=true
fi

write_root_file "$MODPROBE_CONF" "$MODPROBE_BODY"
write_root_file "$SYSCTL_CONF" "$SYSCTL_BODY"

# modprobe.d is copied into the initramfs by the modconf hook, and the nvidia
# modules load from there (see install-drivers.sh), so the options only take
# effect once the image is rebuilt.
if [ "$needs_initramfs" = true ]; then
    info "Regenerating initramfs for the new nvidia module options..."
    run_quiet sudo mkinitcpio -P
fi

info "Applying sysctl settings..."
run_quiet sudo sysctl --system

ok "kernel and driver tunables configured"

if [ "$needs_initramfs" = true ]; then
    warn "reboot required for the nvidia module options to take effect"
fi
