#!/bin/bash
source "$(dirname "${BASH_SOURCE[0]}")/../../lib/common.sh"

require_cmd sysctl

SYSCTL_CONF="/etc/sysctl.d/99-gaming.conf"

SYSCTL_BODY="# Generated by install-scripts/modules/base/install-tunables.sh -- edit there.
#
# split_lock_mitigate does not prevent split locks, it penalises the process
# that takes one with a forced delay. Windows games under Proton trigger them
# routinely, which shows up as periodic hitching at a healthy average FPS.
kernel.split_lock_mitigate = 0

# Stop the kernel paging out game memory it thinks is cold during a long
# session; touching it again later is a stall.
vm.swappiness = 10"

# write_root_file runs sudo tee inside a pipe, so credentials must already
# be cached.
prime_sudo

write_root_file "$SYSCTL_CONF" "$SYSCTL_BODY"

info "Applying sysctl settings..."
run_quiet sudo sysctl --system

ok "kernel tunables configured"
